server:
  port: 8080

downstream:
  base-url: ${DOWNSTREAM_BASE_URL}

management:
  observations:
    key-values:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true  # 開啟這行，才會產生 _bucket 指標
      sla:
        http.server.requests: 0.1s, 0.5s, 1s, 2s  # 手動定義桶子邊界

spring:
  application:
    name: observable-main