services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-gateway/conf.d:/etc/nginx/conf.d:ro
    networks: [ web ]
  main:
    build:
      context: .
      dockerfile: observable-main/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DOWNSTREAM_BASE_URL=http://downstream:8080

  downstream:
    build:
      context: .
      dockerfile: observable-downstream/Dockerfile

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/'
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: always
    networks: [ web ]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.26.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"

networks:
  web: