services:
  main:
    build:
      context: .
      dockerfile: observable-main/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DOWNSTREAM_BASE_URL=http://downstream:8080

  downstream:
    build:
      context: .
      dockerfile: observable-downstream/Dockerfile
    ports:
      - "8081:8081"
    networks:
      default:
        aliases:
          - downstream # 為這個服務取一個別名