services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-gateway/conf.d:/etc/nginx/conf.d:ro
    networks: [ web ]
    depends_on: [prometheus, grafana, alertmanager, main]
  main:
    build:
      context: .
      dockerfile: observable-main/Dockerfile
    networks: [ web ]
    environment:
      - DOWNSTREAM_BASE_URL=http://downstream:8080

  downstream:
    build:
      context: .
      dockerfile: observable-downstream/Dockerfile
    networks: [ web ]

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/'
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: always
    networks: [ web ]

  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
     - GF_SERVER_ROOT_URL=http://${PUBLIC_IP:-localhost}/grafana/
     - GF_SERVER_SERVE_FROM_SUB_PATH=false
    networks: [ web ]

  alertmanager:
    image: prom/alertmanager:v0.26.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks: [ web ]
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.route-prefix=/'
      - '--web.external-url=http://${PUBLIC_IP:-localhost}/alertmanager/'

networks:
  web: