global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'main'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'main:8080' ]
        labels:
          service: 'main'
  - job_name: 'downstream'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'downstream:8080' ]
        labels:
          service: 'downstream'